# Generated by Django 3.2.9 on 2021-12-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_db',
            old_name='Email_id',
            new_name='email_id',
        ),
        migrations.RemoveField(
            model_name='user_db',
            name='user_name',
        ),
    ]
