# Generated by Django 3.2.9 on 2021-12-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_user_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_db',
            name='address',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
