# Generated by Django 3.2.9 on 2021-12-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_alter_user_db_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_db',
            name='name',
        ),
        migrations.AddField(
            model_name='user_db',
            name='first_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user_db',
            name='last_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
