# Generated by Django 3.2.9 on 2022-02-24 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_title', models.CharField(max_length=200)),
                ('threat', models.CharField(max_length=500)),
                ('crime_description', models.TextField()),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
                ('status', models.CharField(default='Registered', max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('complainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Police_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.IntegerField()),
                ('police_id', models.CharField(max_length=128)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_description', models.TextField()),
                ('comments', models.CharField(blank=True, max_length=128, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='police_panel.complaint')),
                ('officer_incharge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='police_panel.police_db')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='police_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='police_panel.police_db'),
        ),
    ]
