# Generated by Django 3.2.9 on 2021-12-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='police_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='police_panel.police_db'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Registered', max_length=50),
        ),
    ]
