# Generated by Django 3.2.9 on 2021-12-17 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('police_panel', '0002_auto_20211217_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='police_db',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_description', models.TextField()),
                ('comments', models.CharField(blank=True, max_length=128, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='police_panel.complaint')),
                ('officer_incharge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='police_panel.police_db')),
            ],
        ),
    ]
